export const AXIOS_ACTION_TYPE = {
  AXIOS_START: "AXIOS_START",
  AXIOS_SUCCESS: "AXIOS_SUCCESS",
  AXIOS_ERROR: "AXIOS_ERROR",
  AXIOS_RESET: "AXIOS_RESET",
};
export const FORM_ACTION_TYPE = {
  CHANGE_INPUT: "CHANGE_INPUT",
  FORM_ERROR: "FORM_ERROR",
};
